events {}

http {
  upstream product_service_replicas {
    server product-service:3003;
  }

  server {
    listen 3003;

    location / {
      proxy_pass http://product_service_replicas;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
